### ISSUE TITLE
Want to collaborate? Please add your Github account and email below.

### ISSUE THREAD

**Issue by jindongwang** [allmachinelearning/MachineLearning#1]
## Please add your **Github account** and email below.

Please mention that you **want to be a maintainer** If you have been a veteran in this area：
- For **machine learning**, just add your info in this isssue;
- For **reinforcement learning**, refer to this issue: https://github.com/allmachinelearning/ReinforcementLearning/issues/4
- For **transfer learning**, refer to this issue: https://github.com/allmachinelearning/TransferLearning/issues/1
- For **Distributed System Design for Deep Learning**, refer to this issue: https://github.com/allmachinelearning/Deep-Learning-System-Design/issues/1

### Also we recommend you use your School Mail or OfficialI Institution Mail.

**Comment by daifen1** [comment]
## invited

account:daifen1  email:w19940926@163.com   915955493@qq.com

**Comment by wildwind0** [comment]
Could not find your account. Could you provide your account name? 

wildwind2333@gmail.com

**Comment by lanlingkukusheng** [comment]
## Confirmed

 email：myworld.my2008@163.com

**Comment by silverbulletmdc** [comment]
## Confirmed

account: silverbulletmdc

email: mengdechaolive@qq.com

**Comment by xiahaoyun** [comment]
## invited

account: xiahaoyun
email: xiahaoyun@outlook.com

**Comment by Coder-Leon** [comment]
## invited

account: Coder-Leon
email: liuqingliang23@outlook.com

**Comment by Jialin28** [comment]
## invited
account:Jialin28
gmail:Jialino102@gmail.com

**Comment by HQCfly** [comment]
## invited

账号：hqcfly
电子邮件:2249629867@qq.com

**Comment by lyjdwh** [comment]
账号lyjdwh
电子邮件：lyjdwh@gmail.com

**Comment by lyjdwh** [comment]
账号:lyjdwh
电子邮件: 1412511544@qq.com

**Comment by csn6666** [comment]
Done
---
account: caisinong
email: caisinong@gmail.com

**Comment by csjxchen** [comment]
Done
---
account:DFGER
email:cjx805662439@gmail.com

**Comment by shizhediao** [comment]
## invited

account: victordiao
email: 654745845@qq.com

**Comment by TairanHu** [comment]
Done
---
account: TairanHu
email: wit_hutairan@163.com

**Comment by polysun** [comment]
Done
---
account: polysun
email: maxfunction@sina.com

**Comment by BrianYang2013** [comment]
Done
---
Account: BrianYang2013
Email: brian.b.yang@gmail.com

**Comment by himicrain** [comment]
Done
---
account : himicrain
email : himicrain@gmail.com

**Comment by Bayesfield** [comment]
Done
-------
account : GD
email : 1015731979@qq.com

**Comment by Andor-Z** [comment]
Done
-----------------
account : Andor-Z
email : zyfsta@outlook.com

**Comment by danielgy** [comment]
Done
-------------------
account: danielgy
emial: 471379891@qq.com

**Comment by yxma2015** [comment]
## already a collaborator.

account: **YaxiongMa** 
email: marathon.1992@qq.com

**Comment by John-Zuo** [comment]
Done
---
account:  John-Zuo
email:    326259666@qq.com

**Comment by MapleHalloween** [comment]
Done
---
account: MapleHalloween
emial: 1831418574@qq.com

**Comment by Nativeatom** [comment]
##  already a collaborator. You can create new topics, write, even delete files.

account: Nativeatom
emial: bill.lyy.nisioptimum@gmail.com

**Comment by wildwind0** [comment]
## invited

account: wildwind0
email: wilidwind2333@gmail.com

**Comment by NomoreMc** [comment]
##  invited

account：NomoreMc
email：nomoremc@163.com

**Comment by DaihuaWei** [comment]
Done
---
account: DaihuaWei
email: david1936@163.com

**Comment by deyuhua** [comment]
account: deyuhua
email: deyuhua@gmail.com

**Comment by jeffrey-antoine** [comment]
account: jeffrey-antoine
email: piaoxiangdahai@hotmail.com

**Comment by Y-WJ** [comment]
account:Dog-Master
1715283607@qq.com
ywj199361@gamil.com

**Comment by xiang-xx** [comment]
invited

account: xiang2017
email: xiang9311@sina.cn

**Comment by xiaolei-chen** [comment]
invited

account: xiaolei-chen
email: 409723485@qq.com

**Comment by dazeq** [comment]
invited

account：yannshuys
email：yannshuys@gmail.com

**Comment by linly74** [comment]
## invited. check your mailbox, please.

account: linly74
email: 438476078@qq.com

I sincerely hope that we can progress with everyone, and explore the field of common problems.

**Comment by wangchenctg** [comment]
Done
---
account:jamesdlut
email:774783106@qq.com

**Comment by sulingling123** [comment]
## Invited

account:  ZoeYuhan
email:  992839215@qq.com

**Comment by way2013** [comment]
### Done

account:way2013
email:pl_2013@126.com

**Comment by Tracyxzh** [comment]
### Done

account:Tracyxzh
email:243307483@qq.com

**Comment by torin96** [comment]
Done

account: qyffWJ
email: 1358321209@qq.com

**Comment by luoxiaoliaolan** [comment]
account:luoxiaoliaolan
email:1512773416@qq.com

**Comment by ChenWentai** [comment]
account: ChenWentai
email: cwentai01@gmail.com

**Comment by zpppy** [comment]
### invited. check your mailbox, please.

account: zpppy
email: 2281678703@qq.com

**Comment by arki0207** [comment]
account: arki0207
email: 94030276@qq.com

**Comment by diggerdu** [comment]
Done
---
account: diggerdu
email: diggerdu@shu.edu.cn

**Comment by L1aoXingyu** [comment]
Done
---
account: SherlockLiao
email: sherlockliao01@gmail.com

**Comment by zgtmy** [comment]
Done
---
account:zgtmy

email:1026361226@qq.com

**Comment by jindongwang** [comment]
Done, check your email to confirm.

发件人: zgtmy [mailto:notifications@github.com]
发送时间: 2017年5月17日 21:16
收件人: allmachinelearning/MachineLearning <MachineLearning@noreply.github.com>
抄送: Jindong Wang <jindongwang@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [allmachinelearning/MachineLearning] Want to collaborate? Please add your Github account and email below. (#1)


account:zgtmy

email:1026361226@qq.com<mailto:1026361226@qq.com>

**Comment by siyu-npc** [comment]
Done
---
account:swardsman
email:1036014410@qq.com

**Comment by jindongwang** [comment]
Done, please check your email

发件人: swardsman [mailto:notifications@github.com]
发送时间: 2017年5月17日 21:28
收件人: allmachinelearning/MachineLearning <MachineLearning@noreply.github.com>
抄送: Jindong Wang <jindongwang@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [allmachinelearning/MachineLearning] Want to collaborate? Please add your Github account and email below. (#1)


account:swardsman
email:1036014410@qq.com<mailto:1036014410@qq.com>

**Comment by SaberQ** [comment]
Done
---
account:SaberQ
email:332102691@qq.com

**Comment by lyiuy** [comment]
Done
---
account: lyiuy
email: liuyang2005112233@163.com

**Comment by ghost** [comment]
Done
---
account:xixiareme
xixiareone@foxmail.com

**Comment by xixiareme** [comment]
account:xixiareme
xixiareone@foxmail.com

**Comment by ahong007007** [comment]
Done
---
account:ahong007007
ahong007@yeah.net

**Comment by astazyx1991** [comment]
Done
---
account:astazyx1991
astazyx@icloud.com

**Comment by ronniegao** [comment]
Done
---
ronniegao
gao1126213386@163.com

**Comment by opfanswyx** [comment]
Done
---
opfanswyx
opfanswyx@outlook.com

**Comment by mangofan** [comment]
Done
---
account：mangofan
email： 1512491852@qq.com
fresh in github, want do machine learning as well, is that fine just leave my account and email?

**Comment by xuzhongyou** [comment]
xuzhongyou 
936214756@qq.com

**Comment by jindongwang** [comment]
You are already a collaborator, please check your email to verify

祝好
王晋东

On 2017/6/27 13:25:38, xuzhongyou <notifications@github.com> wrote:

xuzhongyou
936214756@qq.com<mailto:936214756@qq.com>

**Comment by elder-frog** [comment]
account: wwh2259253
email: sdwwh2259253@gmail.com

**Comment by jindongwang** [comment]
Done

祝好
王晋东

On 2017/7/3 12:34:25, 吴问涵 <notifications@github.com> wrote:

account: wwh2259253
email: sdwwh2259253@gmail.com<mailto:sdwwh2259253@gmail.com>

**Comment by Guangzhan** [comment]
account:Guangzhan
email:fuzhan713@gmail.com

**Comment by ergui22** [comment]
account:ergui22
email:abdf777@126.com

**Comment by jindongwang** [comment]
@ergui22 Done, please check your email to confirm.

**Comment by jindongwang** [comment]
@Guangzhan Done, please check your email to confirm.
