### ISSUE TITLE
Please add your email below if you want to be a SLACK member

### ISSUE THREAD

**Issue by jindongwang** [allmachinelearning/MachineLearning#10]
I create a **Slack** team of this repo. If you want to join us other than WeChat, feel free to add your email below.

**Comment by xiandong79** [comment]
Done
---
xqiad@connect.ust.hk

**Comment by zjtest23** [comment]
Done
---
zl20111303002@gmail.com

**Comment by shawnRJX** [comment]
Done
---
rjx19910911@gmail.com

**Comment by statham-stone** [comment]
-

**Comment by zgtmy** [comment]
Done
---
1026361226@qq.com

**Comment by zhaxiaomei** [comment]
Done
---
0451liyang@163.com

**Comment by yqx7150** [comment]
Done
---
yqx7150@163.com

**Comment by csjxchen** [comment]
Done
---
jiaxinchen1005@gmail.com

**Comment by siyu-npc** [comment]
Done
---
dreameng2520@hotmail.com

**Comment by imfing** [comment]
Done
---
fingr8@163.com

**Comment by thomaszf** [comment]
Done
---
thomas.zf@hotmail.com

**Comment by gumiaoyuan** [comment]
Done
---
miaoyuangu@gmail.com

**Comment by SilenceOverflow** [comment]
Done
---
autoxiayj@gmail.com

**Comment by ghost** [comment]
Done
---
xixiareone@foxmail.com

**Comment by zhyx12** [comment]
Done
---
zhyx12@gmail.com

**Comment by xuzhongyou** [comment]
Done
---
xuzhongyou
936214756@qq.com

**Comment by elder-frog** [comment]
Done
---
sdwwh2259253@gmail.com

**Comment by icsaas** [comment]
Done
---
matrix.orz@gmail.com

**Comment by jindongwang** [comment]
Please check your email, you have already been invited



On 2017/7/7 18:51:35, codedoc <notifications@github.com> wrote:

matrix.orz@gmail.com<mailto:matrix.orz@gmail.com>

**Comment by TairanHu** [comment]
Done
---
wit_hutairan@163.com

**Comment by csn6666** [comment]
Done
---
caisinong@gmail.com

**Comment by tina-lintian** [comment]
Done
---
lintian.usc@gmail.com

**Comment by KunBetter** [comment]
Done
---
nk05xy@163.com

**Comment by wogong** [comment]
Done
---
hi@wogong.net

thanks :)

**Comment by mikelhsia** [comment]
Done
---
Mikelhsia@hotmail.com<mailto:Mikelhsia@hotmail.com>

Best,
Michael Hsia

On Nov 29, 2017, at 23:04, Cheng Zhen <notifications@github.com<mailto:notifications@github.com>> wrote:


hi@wogong.net<mailto:hi@wogong.net>

thanks :)

**Comment by zodiac911** [comment]
wangtaode090107@hotmail.com

**Comment by Banyi** [comment]
Done
banyiby@163.com

**Comment by RoacherM** [comment]
Sir.housir@gmail.com
