### ISSUE TITLE
科研在线无法创建公开链接

### ISSUE THREAD

**Issue by elder-frog** [allmachinelearning/MachineLearning#11]
上传文件后只能在团队内分享，无法创建公开链接

**Comment by elder-frog** [comment]
文件夹和文件都无法创建公开链接

**Comment by jindongwang** [comment]
That website closed the public link.
**Please try** http://mega.nz
That website has 50GB free storage, so you can create an account and share files.
Sorry about this.

**Comment by elder-frog** [comment]
@jindongwang Copy that _(ゝ｢ｪ:)ﾉ
